name: Detect translation conflicts

on:
  pull_request:
    branches:
      - master

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "SS220Manager"
      - name: Try merging
        continue-on-error: true
        run: |
          git merge origin/translate
          echo "MERGE_CONFLICTS=$(git diff --diff-filter=U)" >> "$GITHUB_ENV"
      - name: Run script
        uses: actions/github-script@v7
        with:
          script: |
            const { MERGE_CONFLICTS } = process.env
            console.log(MERGE_CONFLICTS)

            if(!MERGE_CONFLICTS) {
              return
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `This pr causes following conflicts on translate branch: \`\`\`${MERGE_CONFLICTS}\`\`\` `
            })
